# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MitigationAction',
            new_name='Mitigation',
        ),
    ]
