# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 01:40
from __future__ import unicode_literals

from django.db import migrations

def insert_form_data(apps, schema_editor):
    # Models
    RegistrationType = apps.get_model('mitigation_action', 'RegistrationType')
    Institution = apps.get_model('mitigation_action', 'Institution')
    Status = apps.get_model('mitigation_action', 'Status')
    Finance = apps.get_model('mitigation_action', 'Finance')
    IngeiCompliance = apps.get_model('mitigation_action', 'IngeiCompliance')
    GeographicScale = apps.get_model('mitigation_action', 'GeographicScale')

    # Data
    registration_type_data = [
        'Inscripción por primera vez',
        'Actualización de información de acción de mitigación'
    ]
    institution_data = [
        'MINAE',
        'SINAMECC'
    ]
    status_data = [
        'Planeación',
        'Implementación',
        'Finalizada'
    ]
    finance_data = [
        {
            'name': 'Por obtener',
            'source': ''
        },
        {
            'name': 'Asegurado',
            'source': ''
        }
    ]
    ingei_compliance_data = [
        'Agricultura, silvicultura y otros usos de la tierra (AFOLU)',
        'Procesos industriales y uso de productos',
        'Residuos'
    ]
    geographic_scale_data = [
        'Nacional',
        'Regional',
        'Local'
    ]

    # Clear current data
    RegistrationType.objects.all().delete()
    Institution.objects.all().delete()
    Status.objects.all().delete()
    Finance.objects.all().delete()
    IngeiCompliance.objects.all().delete()
    GeographicScale.objects.all().delete()

    # Insert seed data
    for rt in registration_type_data:
        reg_type = RegistrationType(type=rt)
        reg_type.save()

    for i in institution_data:
        inst = Institution(name=i)
        inst.save()

    for sd in status_data:
        stat = Status(status=sd)
        stat.save()

    for fd in finance_data:
        fin = Finance(name=fd.get('name'), source=fd.get('source'))
        fin.save()

    for icd in ingei_compliance_data:
        ingei = IngeiCompliance(name=icd)
        ingei.save()

    for gsd in geographic_scale_data:
        geo = GeographicScale(name=gsd)
        geo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0002_auto_20180406_0303'),
    ]

    operations = [
        migrations.RunPython(insert_form_data)
    ]
