# Generated by Django 3.2 on 2021-04-22 03:45

from django.db import migrations, models
from mitigation_action.workflow.states import States as FSM_STATE

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0002_auto_20210422_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigationaction',
            name='fsm_state',
            field=models.CharField(max_length=50, default=FSM_STATE.NEW)
        ),
    ]
