# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0003_auto_20180410_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressindicator',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
