
# Generated by Izcar on 2021-04-28 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from mitigation_action.migrations.default_data.data_migration_0005 import _geographic_scale_data, _finance_source_type_data, \
    _finance_status_data, _initiative_type_data, _status_data

def insert_form_data(apps, schema_editor):

    # Models
    InitiativeType = apps.get_model('mitigation_action', 'InitiativeType')
    GeographicScale = apps.get_model('mitigation_action', 'GeographicScale')
    FinanceSourceType = apps.get_model('mitigation_action', 'FinanceSourceType')
    FinanceStatus = apps.get_model('mitigation_action', 'FinanceStatus')
    Status = apps.get_model('mitigation_action', 'Status')

    model_and_data = {
        InitiativeType: _initiative_type_data, GeographicScale: _geographic_scale_data, FinanceSourceType: _finance_source_type_data,
        FinanceStatus: _finance_status_data, Status: _status_data
    }

    for _model, _data in model_and_data.items():
        for _record in _data:
            record = _model(**_record)
            record.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0004_auto_20210428_0114'),
    ]

    operations = [
        migrations.RunPython(insert_form_data)
    ]


