# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0005_auto_20180418_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigation',
            name='question_ucc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
