# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
        ('mitigation_action', '0005_auto_20180418_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_current', to='workflow.ReviewStatus')),
            ],
        ),
        migrations.AddField(
            model_name='mitigation',
            name='comments',
            field=models.ManyToManyField(to='workflow.Comment'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='review_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigation',
            name='review_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='workflow.ReviewStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changelog',
            name='mitigation_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='mitigation_action.Mitigation'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='previous_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_previous', to='workflow.ReviewStatus'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
