# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0006_auto_20180501_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('date',), 'verbose_name': 'ChangeLog', 'verbose_name_plural': 'ChangeLogs'},
        ),
    ]
