# Generated by Django 3.2 on 2021-05-11 05:57

from django.db import migrations, models
import django.db.models.deletion
import general.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0006_auto_20210429_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration', models.TextField(null=True)),
                ('source_description', models.CharField(max_length=255, null=True)),
                ('reference_year', models.IntegerField(null=True, validators=[general.helpers.validators.validate_year])),
                ('budget', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('currency', models.CharField(choices=[('CRC', 'Costa Rican colon'), ('USD', 'United States dollar')], max_length=10, null=True)),
                ('mideplan_registered', models.BooleanField(null=True)),
                ('mideplan_project', models.CharField(max_length=255, null=True)),
                ('executing_entity', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ManyToManyField(blank=True, related_name='finance', to='mitigation_action.financesourcetype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mitigation_action.financestatus')),
                
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finance',
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='finance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.finance'),
            
        ),
    ]
