# Generated by Django 3.2 on 2021-05-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0007_auto_20210511_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_emission', models.TextField(null=True)),
                ('graphic_description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GHG Informaction',
                'verbose_name_plural': 'GHG Informaction',
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='ghg_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.ghginformation'),
        ),
    ]
