# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0007_auto_20180503_0256'),
        ('mitigation_action', '0006_mitigation_question_ucc'),
    ]

    operations = [
    ]
