# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0008_merge_20180505_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
