# Generated by Django 3.2 on 2021-05-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0008_auto_20210511_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_reduction_co2', models.TextField(null=True)),
                ('period_potential_reduction', models.TextField(null=True)),
                ('base_line_definition', models.TextField(null=True)),
                ('calculation_methodology', models.TextField(null=True)),
                ('estimate_calculation_documentation', models.TextField(null=True)),
                ('mitigation_action_in_inventory', models.BooleanField(null=True)),
                ('carbon_international_commerce', models.BooleanField(null=True)),
                ('methodologies_to_use', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Documentation',
                'verbose_name_plural': 'Impact Documentation',
            },
        ),
        migrations.CreateModel(
            name='QAQCReductionEstimateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, null=True)),
                ('question', models.TextField(null=True)),
                ('check', models.BooleanField(null=True)),
                ('detail', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('impact_documentation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='mitigation_action.impactdocumentation')),
            ],
            options={
                'verbose_name': 'Impact Documentation',
                'verbose_name_plural': 'Impact Documentation',
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='impact_documentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_action', to='mitigation_action.impactdocumentation'),
        ),
    ]
