# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0009_auto_20180509_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FinanceSourceType',
                'verbose_name_plural': 'FinanceSourceTypes',
            },
        ),
        migrations.RemoveField(
            model_name='finance',
            name='name',
        ),
        migrations.AddField(
            model_name='finance',
            name='finance_source_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mitigation_action.FinanceSourceType'),
            preserve_default=False,
        ),
    ]
