# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0010_auto_20180512_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigation',
            name='question_ovv',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
