# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0010_auto_20180512_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='comments',
            field=models.ManyToManyField(blank=True, to='workflow.Comment'),
        ),
    ]
