# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 20:42
from __future__ import unicode_literals

from django.db import migrations

def insert_finance_status_data(apps, schema_editor):
    # Models
    FinanceSourceType = apps.get_model('mitigation_action', 'FinanceSourceType')

    # Data
    finance_source_type_data = [
        'Por obtener',
        'Asegurado'
    ]

    # Clear current data
    FinanceSourceType.objects.all().delete()

    # Insert seed data
    for fst in finance_source_type_data:
        finance_source_type = FinanceSourceType(name=fst)
        finance_source_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0010_auto_20180512_2026'),
    ]

    operations = [
        migrations.RunPython(insert_finance_status_data)
    ]
