# Generated by Django 3.2 on 2021-07-21 20:53

from django.db import migrations
from mitigation_action.migrations.default_data.data_migration_0013_1 import _action_areas
from mitigation_action.migrations.default_data.data_migration_0013_2 import _axis_descarbonization_data
from mitigation_action.migrations.default_data.data_migration_0013_3 import _topics_data

def insert_form_data_action_areas(apps, schema_editor):

    # Models
    ActionAreas = apps.get_model('mitigation_action', 'ActionAreas')
    ActionGoals = apps.get_model('mitigation_action', 'ActionGoals')

    for _data in _action_areas:
        goals = _data.pop('goals')
        record = ActionAreas(**_data)
        record.save()
  
        for goal in goals:
            goal_record = ActionGoals(**goal, area=record)
            goal_record.save()



def insert_form_data_descarbonization_axis(apps, schema_editor):

    # Models
    DescarbonizationAxis = apps.get_model('mitigation_action', 'DescarbonizationAxis')
    TransformationalVisions = apps.get_model('mitigation_action', 'TransformationalVisions')

    for _data in _axis_descarbonization_data:
        transformational_vision = _data.pop('transformational_vision')
        record = DescarbonizationAxis(**_data)
        record.save()
        for tv in transformational_vision:
            tv_record = TransformationalVisions(**tv, axis=record)
            tv_record.save()


def insert_form_data_topics(apps, schema_editor):

    # Models
    Topics = apps.get_model('mitigation_action', 'Topics')
    SubTopics = apps.get_model('mitigation_action', 'SubTopics')
    Activity = apps.get_model('mitigation_action', 'Activity')

    for _data in _topics_data:
        sub_topic = _data.pop('sub_topic')
        record = Topics(**_data)
        record.save()
        for st in sub_topic:
            activity = st.pop('activities')
            st_record = SubTopics(**st, topic=record)
            st_record.save()

            for a in activity:
                activity_record = Activity(**a, sub_topic=st_record)
                activity_record.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0012_auto_20210721_2008'),
    ]

    operations = [
        ## reverse if failde RunPython
        migrations.RunPython(insert_form_data_action_areas, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(insert_form_data_descarbonization_axis, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(insert_form_data_topics, reverse_code=migrations.RunPython.noop),
    ]
