# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-26 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0012_mitigation_question_ovv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='previous_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_log_previous', to='workflow.ReviewStatus'),
        ),
    ]
