# Generated by Django 3.2 on 2021-07-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0013_auto_20210721_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part_to_another_mitigation_action', models.BooleanField(null=True)),
                ('relation_description', models.CharField(max_length=255, blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('action_goal', models.ManyToManyField(blank=True, related_name='categorization', to='mitigation_action.ActionGoals')),
                ('activities', models.ManyToManyField(blank=True, related_name='categorization', to='mitigation_action.Activity')),
                ('impact_categories', models.ManyToManyField(blank=True, related_name='categorization', to='mitigation_action.ImpactCategory')),
                ('sub_topics', models.ManyToManyField(blank=True, related_name='categorization', to='mitigation_action.SubTopics')),
                ('transformational_vision', models.ManyToManyField(blank=True, related_name='categorization', to='mitigation_action.TransformationalVisions')),
            ],
            options={
                'verbose_name': 'Categorization',
                'verbose_name_plural': 'Categorization',
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='categorization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.categorization'),
        ),
    ]
