# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models

def insert_form_data(apps, schema_editor):
    # Models
    RegistrationType = apps.get_model('mitigation_action', 'RegistrationType')
    Status = apps.get_model('mitigation_action', 'Status')
   # Finance = apps.get_model('mitigation_action', 'Finance')
    FinanceSourceType = apps.get_model('mitigation_action', 'FinanceSourceType')
    IngeiCompliance = apps.get_model('mitigation_action', 'IngeiCompliance')
    GeographicScale = apps.get_model('mitigation_action', 'GeographicScale')

    # Data
    registration_type_data = [
        {
            'type_es':'Inscripción por primera vez',
            'type_en':'Registration for the first time'
        },
        {
            'type_es':'Actualización de información de acción de mitigación',
            'type_en':'Update of mitigation action information'
        }
    ]

    status_data = [
        {
            'status_es':'Planeación',
            'status_en':'Planning'
        },
        {
            'status_es':'Implementación',
            'status_en':'Implementation'
        },
        {
            'status_es':'Finalizada',
            'status_en':'Completed'
        }
    ]

    finance_source_type_data = [
        {
            'name_es': 'Por obtener',
            'name_en': 'To obtain' },
        {
            'name_es': 'Asegurado',
            'name_en': 'Insured'
        }
    ]
    ingei_compliance_data = [
        {
            'name_es':'Agricultura, silvicultura y otros usos de la tierra (AFOLU)', 
            'name_en':'Agriculture, forestry and other land uses'
        },
        {
            'name_es':'Procesos industriales y uso de productos',
            'name_en':'Industrial processes and use of products'
        },
        {
            'name_es':'Residuos', 
            'name_en':'Residue'
        }
    ]
    geographic_scale_data = [
        {
            'name_es':'Nacional', 
            'name_en':'National'
        },
        {
            'name_es':'Regional', 
            'name_en':'Regional'
        },
        {
            'name_es':'Local', 
            'name_en':'Local'
        }
    ]

    # Clear current data
    RegistrationType.objects.all().delete()
    Status.objects.all().delete()
    FinanceSourceType.objects.all().delete()
    IngeiCompliance.objects.all().delete()
    GeographicScale.objects.all().delete()

    # Insert seed data
    for rt in registration_type_data:
        reg_type = RegistrationType(type_es=rt.get('type_es'), type_en=rt.get('type_en'))
        reg_type.save()

    for sd in status_data:
        stat = Status(status_es=sd.get('status_es'), status_en=sd.get('status_en'))
        stat.save()

    for fst in finance_source_type_data:
        fsty = FinanceSourceType(name_es=fst.get('name_es'), name_en=fst.get('name_en'))
        fsty.save()

    for icd in ingei_compliance_data:
        ingei = IngeiCompliance(name_es=icd.get('name_es'), name_en=icd.get('name_en'))
        ingei.save()

    for gsd in geographic_scale_data:
        geo = GeographicScale(name_es=gsd.get('name_es'), name_en=gsd.get('name_en'))
        geo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0013_auto_20180526_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financesourcetype',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='geographicscale',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='ingeicompliance',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='registrationtype',
            old_name='type',
            new_name='type_en',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='status_en',
        ),
        migrations.AddField(
            model_name='financesourcetype',
            name='name_es',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geographicscale',
            name='name_es',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingeicompliance',
            name='name_es',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='type_es',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='status_es',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(insert_form_data)
    ]
