# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-12 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitigation_action', '0014_auto_20180604_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonizationIngei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to='harmonization_ingei/%Y%m%d/%H%M%S')),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitigation_action.Mitigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonization_ingei', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HarmonizationIngei',
                'verbose_name_plural': 'HarmonizationIngeis',
            },
        ),
    ]
