# Generated by Django 3.2 on 2021-07-29 18:32

from django.db import migrations, models
import general.storages
import mitigation_action.models
from mitigation_action.migrations.default_data.data_migration_0015 import _sustainable_development_goals, _ghg_impact_sector

def insert_form_data(apps, schema_editor):

    # Models
    SustainableDevelopmentGoals = apps.get_model('mitigation_action', 'SustainableDevelopmentGoals')
    GHGImpactSector = apps.get_model('mitigation_action', 'GHGImpactSector')

    model_and_data = {
        SustainableDevelopmentGoals: _sustainable_development_goals,
        GHGImpactSector: _ghg_impact_sector
    }

    for _model, _data in model_and_data.items():
        for _record in _data:
            record = _model(**_record)
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0014_auto_20210729_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHGImpactSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GHG Impact Sector',
                'verbose_name_plural': 'GHG Impact Sectors',
            },
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sustainable Development Goal',
                'verbose_name_plural': 'Sustainable Development Goals',
            },
        ),
        migrations.AddField(
            model_name='ghginformation',
            name='graphic_description_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='ghginformation',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='ghg_information', to='mitigation_action.SustainableDevelopmentGoals'),
        ),
        migrations.AddField(
            model_name='ghginformation',
            name='impact_sector',
            field=models.ManyToManyField(blank=True, related_name='ghg_information', to='mitigation_action.GHGImpactSector'),
        ),
        migrations.RunPython(insert_form_data),
    ]
