# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 20:21
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0014_auto_20180604_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigation',
            name='review_status',
        ),
        migrations.AddField(
            model_name='mitigation',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
