# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0015_harmonizationingei'),
        ('mitigation_action', '0015_registrationtype_type_key'),
    ]

    operations = [
    ]
