# Generated by Django 3.2 on 2021-07-29 19:06

from django.db import migrations, models
import django.db.models.deletion
import general.storages
import mitigation_action.models
from mitigation_action.migrations.default_data.data_migration_0016 import _carbon_deposits, _standards

def insert_form_data(apps, schema_editor):

    # Models
    CarbonDeposit = apps.get_model('mitigation_action', 'CarbonDeposit')
    Standard = apps.get_model('mitigation_action', 'Standard')

    model_and_data = {
        CarbonDeposit: _carbon_deposits,
        Standard: _standards
    }

    for _model, _data in model_and_data.items():
        for _record in _data:
            record = _model(**_record)
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0015_auto_20210729_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carbon Deposit',
                'verbose_name_plural': 'Carbon Deposits',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standar',
                'verbose_name_plural': 'Standars',
            },
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='carbon_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_documentation', to='mitigation_action.carbondeposit'),
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='estimate_calculation_documentation_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='other_standard',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_documentation', to='mitigation_action.standard'),
        ),
        
        migrations.RunPython(insert_form_data),
    ]
