# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


def update_type_key_data(apps, schema_editor):
    RegistrationType = apps.get_model('mitigation_action', 'RegistrationType')

    # Data
    registration_type_data = [
        {
            'type_key':'new',
            'type_es':'Inscripción por primera vez',
            'type_en':'Registration for the first time'
        },
        {
            'type_key': 'update',
            'type_es':'Actualización de información de acción de mitigación',
            'type_en':'Update of mitigation action information'
        }
    ]

    RegistrationType.objects.all().delete()
    for rt in registration_type_data:
        reg_type = RegistrationType(type_key=rt.get('type_key'), type_es=rt.get('type_es'), type_en=rt.get('type_en'))
        reg_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0015_auto_20180722_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='type_key',
            field=models.CharField(default='new', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(update_type_key_data)
    ]
