# Generated by Django 3.2 on 2021-09-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20201028_1950'),
        ('mitigation_action', '0016_auto_20210729_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigationaction',
            name='comments',
            field=models.ManyToManyField(blank=True, to='workflow.Comment'),
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
