# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitigation_action', '0016_merge_20180726_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonizationIngeiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to='harmonization_ingei/%Y%m%d/%H%M%S')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HarmonizationIngeiFile',
                'verbose_name_plural': 'HarmonizationIngeiFiles',
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='harmonizationingei',
            name='file',
        ),
        migrations.RemoveField(
            model_name='harmonizationingei',
            name='mitigation_action',
        ),
        migrations.AddField(
            model_name='harmonizationingei',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='harmonizationingeifile',
            name='harmonization_ingei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitigation_action.HarmonizationIngei'),
        ),
        migrations.AddField(
            model_name='harmonizationingeifile',
            name='mitigation_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitigation_action.Mitigation'),
        ),
        migrations.AddField(
            model_name='harmonizationingeifile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonization_ingei_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
