# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0017_auto_20180726_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonizationingei',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
