# Generated by Django 3.2 on 2022-06-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0018_auto_20220503_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='source_description',
        ),
        migrations.CreateModel(
            name='FinanceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_description', models.CharField(max_length=255, null=True)),
                ('budget', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('currency', models.CharField(choices=[('CRC', 'Costa Rican colon'), ('USD', 'United States dollar'), ('EUR', 'Euro')], max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_information', to='mitigation_action.finance')),
            ],
            options={
                'verbose_name': 'Finance Information',
                'verbose_name_plural': 'Finance Information',
            },
        ),
    ]
