# Generated by Django 3.2 on 2022-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0019_auto_20220503_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='additional_information_file',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='other_classifier',
        ),
        migrations.AlterField(
            model_name='impactdocumentation',
            name='mitigation_action_in_inventory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='informationsource',
            name='type',
        ),
        migrations.AddField(
            model_name='informationsource',
            name='type',
            field=models.ManyToManyField(blank=True, to='mitigation_action.InformationSourceType'),
        ),
    ]
