# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0019_auto_20180803_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='current_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='previous_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
