# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages
import mitigation_action.workflow_steps.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitigation_action', '0020_auto_20180817_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAWorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitigation_action.Mitigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
            },
        ),
        migrations.CreateModel(
            name='MAWorkflowStepFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.workflow_steps.models.workflow_step_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonization_ingei_file', to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitigation_action.MAWorkflowStep')),
            ],
            options={
                'verbose_name': 'Workflow Step File',
                'verbose_name_plural': 'Workflow Step Files',
            },
        ),
        migrations.RemoveField(
            model_name='harmonizationingei',
            name='user',
        ),
        migrations.RemoveField(
            model_name='harmonizationingeifile',
            name='harmonization_ingei',
        ),
        migrations.RemoveField(
            model_name='harmonizationingeifile',
            name='mitigation_action',
        ),
        migrations.RemoveField(
            model_name='harmonizationingeifile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HarmonizationIngei',
        ),
        migrations.DeleteModel(
            name='HarmonizationIngeiFile',
        ),
    ]
