# Generated by Django 3.2 on 2022-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0021_remove_finance_reference_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='reference_year',
            field=models.DateField(null=True),
        ),
    ]
