# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def insert_initiative_type_data(apps, schema_editor):
    InitiativeType = apps.get_model('mitigation_action', 'InitiativeType')
    FinanceStatus = apps.get_model('mitigation_action', 'FinanceStatus')

    # Data
    initiative_type_data = [
        {
            'initiative_type_es':'Proyecto',
            'initiative_type_en':'Proyect'
        },
        {
            'initiative_type_es':'Política',
            'initiative_type_en':'Law'
        },
        {
            'initiative_type_es':'Meta',
            'initiative_type_en':'Goal'
        }

    ]
    finance_status_data = [
        {
            'name_es': 'Por obtener',
            'name_en': 'To obtain'
        },
        {
            'name_es': 'Asegurado',
            'name_en': 'Insured'
        }

    ]
    FinanceStatus.objects.all().delete()
    InitiativeType.objects.all().delete()
    for it in initiative_type_data:
        init_type = InitiativeType(initiative_type_es=it.get('initiative_type_es'), initiative_type_en=it.get('initiative_type_en'))
        init_type.save() 
    
    for fs in finance_status_data:
        init_status = FinanceStatus(name_es=fs.get('name_es'), name_en=fs.get('name_en'))
        init_status.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0022_auto_20180919_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FinanceStatus',
                'verbose_name_plural': 'FinanceStatuses',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('objective', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('goal', models.CharField(max_length=400)),
                ('entity_responsible', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='mitigation_action.Contact')),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
            },
        ),
        migrations.CreateModel(
            name='InitiativeFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_finance_source_type', to='mitigation_action.FinanceSourceType')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_finance_status', to='mitigation_action.FinanceStatus')),
            ],
            options={
                'verbose_name': 'InitiativeFinance',
                'verbose_name_plural': 'InitiativeFinances',
            },
        ),
        migrations.CreateModel(
            name='InitiativeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_type_es', models.CharField(max_length=100)),
                ('initiative_type_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'InitiativeType',
                'verbose_name_plural': 'InitiativeTypes',
            },
        ),
        migrations.RemoveField(
            model_name='finance',
            name='finance_source_type',
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='bibliographic_sources',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='carbon_sinks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Contact'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='emissions_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Finance'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='gas_inventory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='geographic_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.GeographicScale'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='impact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='impact_plan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Institution'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='international_participation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='is_international',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Location'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='progress_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.ProgressIndicator'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='purpose',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='quantitative_purpose',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='question_ovv',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='question_ucc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='registration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.RegistrationType'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Status'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='strategy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='sustainability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mitigation_action.InitiativeFinance'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='initiative_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_type', to='mitigation_action.InitiativeType'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='mitigation_action.Status'),
        ),
        migrations.AddField(
            model_name='finance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_status', to='mitigation_action.FinanceStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigation',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.Initiative'),
        ),
        migrations.RunPython(insert_initiative_type_data)
    ]
