# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-30 02:14
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0022_auto_20180919_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=100, protected=True),
        ),
    ]
