# Generated by Django 3.2 on 2022-06-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0022_finance_reference_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorization',
            name='action_goal',
        ),
        migrations.CreateModel(
            name='ActionAreasSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_area_selection', to='mitigation_action.actionareas')),
                ('categorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_area_selection', to='mitigation_action.categorization')),
                ('goals', models.ManyToManyField(blank=True, related_name='action_area_selection', to='mitigation_action.ActionGoals')),
            ],
        ),
    ]
