# Generated by Django 3.2 on 2022-07-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0022_finance_reference_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorization',
            name='action_goal',
        ),
        migrations.RemoveField(
            model_name='categorization',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='categorization',
            name='impact_categories',
        ),
        migrations.RemoveField(
            model_name='categorization',
            name='sub_topics',
        ),
        migrations.RemoveField(
            model_name='categorization',
            name='transformational_vision',
        ),
        migrations.AddField(
            model_name='categorization',
            name='impact_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorization', to='mitigation_action.impactcategory'),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='relation_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='informationsource',
            name='type',
        ),
        migrations.AddField(
            model_name='informationsource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_source', to='mitigation_action.informationsourcetype'),
        ),
        migrations.CreateModel(
            name='TopicsSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categorization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_selection', to='mitigation_action.categorization')),
                ('sub_topic', models.ManyToManyField(related_name='topics_selection', to='mitigation_action.SubTopics')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_selection', to='mitigation_action.topics')),
            ],
        ),
        migrations.CreateModel(
            name='DescarbonizationAxisSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categorization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='descarbonization_axis_selection', to='mitigation_action.categorization')),
                ('descarbonization_axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descarbonization_axis_selection', to='mitigation_action.descarbonizationaxis')),
                ('transformational_vision', models.ManyToManyField(blank=True, related_name='descarbonization_axis_selection', to='mitigation_action.TransformationalVisions')),
            ],
        ),
        migrations.CreateModel(
            name='ActionAreasSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_area_selection', to='mitigation_action.actionareas')),
                ('categorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_area_selection', to='mitigation_action.categorization')),
                ('goals', models.ManyToManyField(blank=True, related_name='action_area_selection', to='mitigation_action.ActionGoals')),
            ],
        ),
    ]
