# Generated by Django 3.2 on 2022-09-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0023_auto_20220705_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIPCC2006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category IPCC2006',
                'verbose_name_plural': 'Categories IPCC2006',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SectorIPCC2006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_ipcc2006', to='mitigation_action.sector')),
            ],
            options={
                'verbose_name': 'Sector IPCC2006',
                'verbose_name_plural': 'Sectors IPCC2006',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryIPCC2006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_ipcc_2006', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sector_ipcc2006', to='mitigation_action.categoryipcc2006')),
            ],
            options={
                'verbose_name': 'Subcategory IPCC2006',
                'verbose_name_plural': 'Subcategories IPCC2006',
            },
        ),
        migrations.CreateModel(
            name='SectorSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_ipcc2006', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_selection', to='mitigation_action.categoryipcc2006')),
                ('impact_documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_selection', to='mitigation_action.impactdocumentation')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_selection', to='mitigation_action.sector')),
                ('sector_ipcc2006', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_selection', to='mitigation_action.sectoripcc2006')),
                ('sub_category_ipcc2006', models.ManyToManyField(related_name='sector_selection', to='mitigation_action.SubCategoryIPCC2006')),
            ],
        ),
        migrations.AddField(
            model_name='categoryipcc2006',
            name='sector_ipcc_2006',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ipcc2006', to='mitigation_action.sectoripcc2006'),
        ),
    ]
