# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0023_auto_20181029_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
