# Generated by Django 3.2 on 2022-10-12 23:24

from django.db import migrations, models
import general.storages
import mitigation_action.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0024_auto_20220920_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='classifier',
            field=models.ManyToManyField(blank=True, related_name='indicator', to='mitigation_action.Classifier'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ensure_sustainability',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ensure_sustainability_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicator',
            name='other_classifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='impactdocumentation',
            name='carbon_deposit',
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='carbon_deposit',
            field=models.ManyToManyField(blank=True, related_name='impact_documentation', to='mitigation_action.CarbonDeposit'),
        ),
        migrations.RemoveField(
            model_name='informationsource',
            name='type',
        ),
        migrations.AddField(
            model_name='informationsource',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='information_source', to='mitigation_action.InformationSourceType'),
        ),
    ]
