# Generated by Django 3.2 on 2022-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0024_auto_20220920_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactdocumentation',
            name='gases',
            field=models.TextField(null=True),
        ),
    ]
