# Generated by Django 3.2 on 2022-10-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0025_auto_20221012_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactdocumentation',
            name='gases',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='impactdocumentation',
            name='carbon_deposit',
        ),
        migrations.AddField(
            model_name='impactdocumentation',
            name='carbon_deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_documentation', to='mitigation_action.carbondeposit'),
        ),
    ]
