# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0025_merge_20181030_1721'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='mitigation',
            name='question_ovv',
        ),
        migrations.RemoveField(
            model_name='mitigation',
            name='question_ucc',
        ),
        migrations.RemoveField(
            model_name='mitigation',
            name='quantitative_purpose'
        ),
        migrations.RemoveField(
            model_name='mitigation',
            name='sustainability'
        ),
        migrations.RenameField(
            model_name='mitigation',
            old_name='bibliographic_sources',
            new_name='calculation_methodology',
        ),
        migrations.AddField(
            model_name='initiativefinance',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
