# Generated by Django 3.2 on 2022-10-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0025_auto_20221012_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactdocumentation',
            name='gases',
            field=models.TextField(null=True),
        ),
    ]
