# Generated by Django 3.2 on 2023-02-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0027_auto_20221121_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinformation',
            name='other_currency',
            field=models.TextField(null=True),
        ),
    ]
