# Generated by Django 3.2 on 2023-03-15 22:09

from django.db import migrations, models
import general.storages
import mitigation_action.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0027_auto_20221121_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='reference_year',
        ),
        migrations.AddField(
            model_name='financeinformation',
            name='reference_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='monitoringindicator',
            name='progress_report_period_until',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='monitoringindicator',
            name='report_line_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monitoringindicator',
            name='report_line_text_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='monitoringindicator',
            name='web_service_conection',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monitoringindicator',
            name='web_service_conection_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=mitigation_action.models.directory_path),
        ),
        migrations.AlterField(
            model_name='financeinformation',
            name='currency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_periodicity',
            field=models.TextField(choices=[('YEARLY', 'Yearly'), ('BIANNUAL', 'Biannual'), ('QUARTERLY', 'Quartely'), ('OTHER', 'Other')], default='YEARLY', max_length=50, null=True),
        ),
    ]
