# Generated by Django 5.1.5 on 2025-05-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0028_auto_20230315_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='ghg_indicator_base',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='ghg_indicator_goal',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
