# Generated by Django 5.1.5 on 2025-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0028_auto_20230315_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeinformation',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
