# Generated by Django 5.1.5 on 2025-06-18 18:57

import django.db.models.deletion
import mitigation_action.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mitigation_action', '0029_indicator_ghg_indicator_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographiclocation',
            name='location_file',
        ),
        migrations.RemoveField(
            model_name='ghginformation',
            name='graphic_description_file',
        ),
        migrations.RemoveField(
            model_name='impactdocumentation',
            name='estimate_calculation_documentation_file',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='ensure_sustainability_file',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='methodological_detail_file',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='description_file',
        ),
        migrations.RemoveField(
            model_name='monitoringindicator',
            name='report_line_text_file',
        ),
        migrations.RemoveField(
            model_name='monitoringindicator',
            name='updated_data_file',
        ),
        migrations.RemoveField(
            model_name='monitoringindicator',
            name='web_service_conection_file',
        ),
        migrations.CreateModel(
            name='GenericFileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mitigation_action.models._directory_file_path)),
                ('type', models.CharField(choices=[('initiative', 'Initiative'), ('geographic-location', 'Geographic Location'), ('ghg-information', 'GHG Information'), ('impact-documentation', 'Impact Documentation'), ('indicator-sustainability', 'Indicator Sustainability'), ('indicator-methodological-detail', 'Indicator Methodological Detail'), ('monitoring-report-line-text', 'Monitoring Report Line Text'), ('monitoring-updated-data', 'Monitoring Updated Data'), ('monitoring-web-service-connection', 'Monitoring Web Service Connection')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('object_id', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_files', to='mitigation_action.mitigationaction')),
            ],
            options={
                'verbose_name': 'Generic File Storage',
                'verbose_name_plural': 'Generic File Storage',
            },
        ),
    ]
