# Generated by Django 5.1.5 on 2025-08-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0031_categoryoption_categoryresult_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='mitigation_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='mitigation_action.mitigationaction'),
        ),
    ]
