# Generated by Django 5.1.5 on 2025-09-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0032_indicator_mitigation_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barrier Option',
                'verbose_name_plural': 'Barrier Options',
            },
        ),
        migrations.CreateModel(
            name='OtherBarrierOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Other Barrier Option',
                'verbose_name_plural': 'Other Barrier Options',
            },
        ),
        migrations.CreateModel(
            name='ImpactIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(max_length=1000, null=True)),
                ('short_term', models.CharField(max_length=1000, null=True)),
                ('medium_term', models.CharField(max_length=1000, null=True)),
                ('long_term', models.CharField(max_length=1000, null=True)),
                ('is_directly_addressed', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('barrier_option', models.ManyToManyField(blank=True, related_name='barrier_ma', to='mitigation_action.barrieroption')),
                ('other_barrier_option', models.ManyToManyField(blank=True, related_name='barrier_ma', to='mitigation_action.otherbarrieroption')),
            ],
            options={
                'verbose_name': 'Impact Identification',
                'verbose_name_plural': 'Impact Identifications',
            },
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='impact_identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_action', to='mitigation_action.impactidentification'),
        ),
    ]
