# Generated by Django 5.1.5 on 2025-09-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_insert_caracteristics'),
        ('mitigation_action', '0033_barrieroption_otherbarrieroption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='specificimpact',
            name='category_ct',
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_impacts_ma', to='general.characteristic'),
        ),
    ]
