# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(id=1, name=u'general_administrator'),
        Group(id=2, name=u'registry_operator'),
        Group(id=3, name=u'mitigation_action_responsible'),
        Group(id=4, name=u'ppcn_responsible'),
        Group(id=5, name=u'pgai'),
        Group(id=6, name=u'validation_organization'),
        Group(id=7, name=u'government_representative'),
        Group(id=8, name=u'data_analyst'),
        Group(id=9, name=u'non_governmental_data_provider'),
        Group(id=10, name=u'inventory_compiler'),
        Group(id=11, name=u'dcc_ppcn_responsible'),
        Group(id=12, name=u'dcc_mitigation_action_responsible'),
        Group(id=13, name=u'dcc_executive_secretary'),
        Group(id=14, name=u'general_user'),
        Group(id=15, name=u'ppcn_provider'),
        Group(id=16, name=u'mitigation_action_provider'),

    ])

    CustomGroup = apps.get_model('users', 'CustomGroup')
    CustomGroup.objects.bulk_create([
        CustomGroup(label=u'General Administrator', group_id=1),
        CustomGroup(label=u'Registry Operator', group_id=2),
        CustomGroup(label=u'Mitigation Action Responsible', group_id=3),
        CustomGroup(label=u'PPCN Responsible', group_id=4),
        CustomGroup(label=u'PGAI', group_id=5),
        CustomGroup(label=u'Validation Organization', group_id=6),
        CustomGroup(label=u'Government Representative', group_id=7),
        CustomGroup(label=u'Data Analyst', group_id=8),
        CustomGroup(label=u'Non-governmental Data Provider', group_id=9),
        CustomGroup(label=u'Inventory Compiler', group_id=10),
        CustomGroup(label=u'DCC of PPCN Responsible', group_id=11),
        CustomGroup(label=u'DCC Mitigation Action Responsible', group_id=12),
        CustomGroup(label=u'DCC Executive Secretary', group_id=13),
        CustomGroup(label=u'General User', group_id=14),
        CustomGroup(label=u'PPCN Provider', group_id=15),
        CustomGroup(label=u'Mitigation Action Provider', group_id=16),
    ])

def revert_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[
        'General Administrator',
        'Registry Operator',
        'Mitigation Action Responsible',
        'PPCN Responsible',
        'PGAI',
        'Validation Organization',
        'Government Representative',
        'Data Analyst',
        'Non-governmental Data Provider',
        'Inventory Compiler',
        'DCC of PPCN Responsible',
        'DCC Mitigation Action Responsible',
        'DCC Executive Secretary',
        'General User',
        'PPCN Provider'

    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'CustomGroup',
                'verbose_name_plural': 'CustomGroups',
            },
        ),
        migrations.RunPython(revert_initial_groups),
        migrations.RunPython(create_initial_groups)
    ]
