# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-05 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_addPermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to=users.models.profile_picture_path)),
                ('current', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
