# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_addPermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_administrador_dcc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_group', to='auth.Group'),
        ),
    ]
