# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_addPermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
