
services:
  db:
    image: postgres:16.0
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: 
      context: .
      dockerfile: ./build/Dockerfile.dev

    command: python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env

    volumes:
      - .:/code

    ports:
      - "8000:8000"

    depends_on:
      - db
volumes:
  postgres_data:
