version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
