version: '3'

services:
  db:
    image: postgres
    volumes:
    - ./sql/sinamecc_db.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db