#!/bin/bash
if [[ -z $SINAMECC_USERNAME || -z $SINAMECC_PASSWORD ]]; then
	username=admin
	password=cambiame
else
	username=$SINAMECC_USERNAME
	password=$SINAMECC_PASSWORD
fi;

sinamecc_host=localhost:8000

token=`curl -s -X POST -H "Content-Type: application/json" -d "{\"username\":\"$username\",\"password\":\"$password\"}" http://${sinamecc_host}/api/v1/token/ | python -mjson.tool | awk -F: '/token/{print $2}'|sed -e 's/\"//g'|tr -d '[:space:]'`

echo "JWT $token"
