# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mccr', '0004_initial_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mccrfile',
            name='mccr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mccr.MCCRRegistry'),
        ),
    ]
