# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        ('mccr', '0005_auto_20180514_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccrfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mccrfile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mccrfile',
            name='file',
            field=models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to='mccr/%Y%m%d/%H%M%S'),
        ),
    ]
