# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def insert_ovv_data(apps, schema_editor):
    OVV = apps.get_model('mccr', 'OVV')

    ovv_data = [
        {
            "name": "Test backend OVV",
            "email": "sinamec@grupoincocr.com",
            "phone": "(506) 9309-2345"
        }
    ]

    OVV.objects.all().delete()
    for o in ovv_data:
        ovv = OVV(name=o.get("name"), email=o.get("email"), phone=o.get("phone"))
        ovv.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mccr', '0006_auto_20180726_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCCRRegistryOVVRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCCR OVV Relation',
                'verbose_name_plural': 'MCCR OVV Relations',
            },
        ),
        migrations.CreateModel(
            name='OVV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organismo Validador Verifador',
                'verbose_name_plural': 'Organismos Validadores Verificadores',
            },
        ),
        migrations.AddField(
            model_name='mccrregistry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mccrregistry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mccrregistryovvrelation',
            name='mccr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mccr.MCCRRegistry'),
        ),
        migrations.AddField(
            model_name='mccrregistryovvrelation',
            name='ovv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mccr.OVV'),
        ),
        migrations.RunPython(insert_ovv_data)
    ]
