# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import general.storages
import mccr.workflow_steps.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mccr', '0007_auto_20180803_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=100, null=True)),
                ('current_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ChangeLog',
                'verbose_name_plural': 'ChangeLogs',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='MCCRWorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCCRWorkflowStepFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to=mccr.workflow_steps.models.workflow_step_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_file', to='mccr.MCCRWorkflowStep')),
            ],
            options={
                'verbose_name': 'Workflow Step File',
                'verbose_name_plural': 'Workflow Step Files',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mccrregistry',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='mccrworkflowstep',
            name='mccr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step', to='mccr.MCCRRegistry'),
        ),
        migrations.AddField(
            model_name='mccrworkflowstep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changelog',
            name='ppcn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='mccr.MCCRRegistry'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_mccr', to=settings.AUTH_USER_MODEL),
        ),
    ]
