# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-25 17:39
from __future__ import unicode_literals
from mccr.models import MCCRRegistry
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
from django.db import migrations

def createPermissions(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(MCCRRegistry)
    permission = MCCRRegistry._meta.permissions
    Permission.objects.bulk_create([Permission(codename=perm[0], name=perm[1], content_type=content_type) for perm in permission ])

class Migration(migrations.Migration):

    dependencies = [
        ('mccr', '0008_auto_20181003_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mccrregistry',
            options={'permissions': (('user_dcc_permission', 'user DCC permision MCCR'), ('user_executive_secretary_permission', 'user executive secretary permission MCCR'), ('user_validating_organizations_permission', 'User Validating Organizations MCCR'), ('can_provide_information', 'Can provide information MCCR'), ('user_executive_committee_permissions', 'User Executive Committee MCCR')), 'verbose_name': 'MCCRRegistry', 'verbose_name_plural': 'MCCRRegistries'},
        ),
        migrations.RunPython(createPermissions)
    ]
