# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-01 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mccr', '0009_addPermissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelog',
            old_name='ppcn',
            new_name='mccr',
        ),
    ]
