# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 16:39
from __future__ import unicode_literals

from django.db import models, migrations

def create_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'General Administrator'),
        Group(name=u'Registry Operator'),
        Group(name=u'Mitigation Action Responsible'),
        Group(name=u'PPCN Responsible'),
        Group(name=u'PGAI'),
        Group(name=u'Validation Organization'),
        Group(name=u'Government Representative'),
        Group(name=u'Data Analyst'),
        Group(name=u'Non-governmental Data Provider'),
        Group(name=u'Inventory Compiler'),
        Group(name=u'General User'),
    ])

def revert_initial_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name_in=[
        u'General Administrator',
        u'Registry Operator',
        u'Mitigation Action Responsible',
        u'PPCN Responsible',
        u'PGAI',
        u'Validation Organization',
        u'Government Representative',
        u'Data Analyst',
        u'Non-governmental Data Provider',
        u'Inventory Compiler',
        u'General User'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_groups, revert_initial_groups)
    ]
