# Generated by Django 3.2 on 2022-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='app_scale',
            field=models.TextField(null=True),
        ),
    ]
