# Generated by Django 3.2 on 2022-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_address_app_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='address', to='general.District'),
        ),
    ]
