# Generated by Django 3.2 on 2022-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20220714_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='canton',
            field=models.ManyToManyField(blank=True, related_name='address', to='general.Canton'),
        ),
    ]
