# Generated by Django 5.1.5 on 2025-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_address_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ManyToManyField(blank=True, related_name='address', to='general.province'),
        ),
    ]
