# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeiOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=200)),
                ('ovv', models.CharField(max_length=200)),
                ('emision_OVV', models.DateField()),
                ('report_date', models.DateField()),
                ('base_year', models.DateField()),
            ],
            options={
                'verbose_name': 'GeiOrganization',
                'verbose_name_plural': 'GeiOrganization',
            },
        ),
        migrations.CreateModel(
            name='RecognitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_type_es', models.CharField(max_length=200)),
                ('recognition_type_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'RecognitionType',
                'verbose_name_plural': 'RecognitionTypes',
            },
        ),
        migrations.CreateModel(
            name='RequiredLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type_es', models.CharField(max_length=200)),
                ('level_type_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'RequiredLevel',
                'verbose_name_plural': 'RequiredLevels',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'SubSector',
                'verbose_name_plural': 'SubSectors',
            },
        ),
        migrations.RenameModel(
            old_name='Level',
            new_name='GeographicLevel',
        ),
        migrations.RemoveField(
            model_name='requestppcn',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='geographiclevel',
            options={'verbose_name': 'GeographicLevel', 'verbose_name_plural': 'GeographicLevels'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='level',
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ciiu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='RequestPpcn',
        ),
    ]
