# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 01:40
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion
def insert_form_data(apps, schema_editor):
    # Models
    GeographicLevel = apps.get_model('ppcn', 'GeographicLevel')
    RequiredLevel = apps.get_model('ppcn', 'RequiredLevel')
    RecognitionType = apps.get_model('ppcn', 'RecognitionType')
    Sector = apps.get_model('ppcn', 'Sector')
    SubSector = apps.get_model('ppcn', 'SubSector')

    # Data
    geographic_level = [
        {
            'level_es': 'Cantonal',
            'level_en': 'Cantonal'
        },
        {
            'level_es': 'Nacional',
            'level_en': 'National'
        }
    ]
    required_level = [
        {
            'level_type_es': 'Solicitud inicial de incorporación al PPCN',
            'level_type_en': 'Initial Request to incorporate with PPCN'
        },
        {
            'level_type_es': 'Mantenimiento en el PPCN',
            'level_type_en': 'Maintenance to PPCN'
        },
        {
            'level_type_es': 'Renovación en el PPCN',
            'level_type_en': 'Renovation in the PPCN'
        }
    ]
    recognition_type = [
        {
            'recognition_type_es': 'Carbono Inventario',
            'recognition_type_en': 'Carbon Inventary'
        },
        {
            'recognition_type_es': 'Carbono Reducción',
            'recognition_type_en': 'Carbon Reduction'
        },
        {
            'recognition_type_es': 'Carbono Reducción +',
            'recognition_type_en': 'Carbon Reduction +'
        },
        {
            'recognition_type_es': 'Carbono Neutral',
            'recognition_type_en': 'Carbon Neutral'
        },
        {
            'recognition_type_es': 'Carbono Neutral +',
            'recognition_type_en': 'Carbon Neutral +'
        }
    ]
    sector = [
        {
            'name_es': 'Energía',
            'name_en': 'Energy',
            'geographicLevel_id' : 2
        },
        {
            'name_es': 'Procesos Industriales',
            'name_en': 'Industrial Processes',
            'geographicLevel_id' : 2
        },
        {
            'name_es': 'Agricultura',
            'name_en': 'Agriculture',
            'geographicLevel_id' : 2
        },
        {
            'name_es': 'Residuos',
            'name_en': 'Waste',
            'geographicLevel_id' : 2
        },
        {
            'name_es': 'Uso de Suelo, Cambio de Suelo y Silvicultura (USCUSyS)',
            'name_en': 'Land Use, Land Change and Forestry (USCUSyS)',
            'geographicLevel_id' : 2
        },
        {
            'name_es':'Energía Estacionaria',
            'name_en': 'Stationary Energy',
            'geographicLevel_id': 1
        }, 
        {
            'name_es':'Transporte',
            'name_en': 'Transport',
            'geographicLevel_id': 1
        }, 
        {
            'name_es':'Residuos',
            'name_en': 'Waste',
            'geographicLevel_id': 1
        }, 
        {
            'name_es':'Agricultura, Silvicultura y Otros Usos de la Tierra',
            'name_en': 'Agriculture, Forestry and Other Uses of the Earth',
            'geographicLevel_id': 1
        }, 
    ]
    sub_sector = [
        {
            'name_es': 'Consumo de combustibles fósiles',
            'name_en': 'Consumption of fossil fuels',
            'sector': 1
        },
        {
            'name_es': 'Emisiones fugitivas',
            'name_en': 'Fugitive emissions',
            'sector': 1
        },
        {
            'name_es': 'Emisiones GEI por quema de biomasa',
            'name_en': 'GEI emissions from burning biomass',
            'sector': 1
        },
        {
            'name_es': 'Distribución de energía',
            'name_en': 'Energy Distribution',
            'sector': 1
        },
        {
            'name_es': 'Productos materiales',
            'name_en': 'Material products',
            'sector': 2
        },
        {
            'name_es': 'Industria química',
            'name_en': 'Chemistry Industry',
            'sector': 2
        },
        {
            'name_es': 'Producción de metales',
            'name_en': 'Metal production',
            'sector': 2
        },
        {
            'name_es': 'Otros procesos industriales',
            'name_en': 'Other industrial processes',
            'sector': 2
        },
        {
            'name_es': 'Producción de halocarbonos y hexafloruro de azufre',
            'name_en': 'Production of halocarbons and sulfur hexafluoride',
            'sector': 2
        },
        {
            'name_es': 'Consumo de halocarbonos y haxafloruro de azufre',
            'name_en': 'Consumption of halocarbons and sulfur hexafluoride',
            'sector': 2
        },
        {
            'name_es': 'Fermentación entérica',
            'name_en': 'Enteric fermentation',
            'sector': 3
        },
        {
            'name_es': 'Manejo de estiércol',
            'name_en': 'Manure management',
            'sector': 3
        },
        {
            'name_es': 'Cultivo del arroz',
            'name_en': 'Rice cultivation',
            'sector': 3
        },
        {
            'name_es': 'Suelos agrícolas',
            'name_en': 'Agricultural soils',
            'sector': 3
        },
        {
            'name_es': 'Quemas programadas de suelos',
            'name_en': 'Scheduled burns of floors',
            'sector': 3
        },
        {
            'name_es': 'Quema in situ de residuos agrícolas',
            'name_en': 'On-site burning of agricultural wastee',
            'sector': 3
        },
        {
            'name_es': 'Disposición de residuos sólidos en suelo',
            'name_en': 'Disposal of solid waste in soil',
            'sector': 4
        },
        {
            'name_es': 'Manejo y tratamiento de aguas residuales',
            'name_en': 'Wastewater treatment and treatment',
            'sector': 4
        },
        {
            'name_es': 'Incineración de residuos',
            'name_en': 'Waste incineration',
            'sector': 4
        },
        {
            'name_es': 'Tierras',
            'name_en': 'Lands',
            'sector': 5
        },
        {
            'name_es':'Edificios residenciales',
            'name_en': 'Residential buildings',
            'sector':6
        },
        {
            'name_es':'Edificios e instalaciones comerciales e institucionales',
            'name_en': 'Commercial and institutional buildings and facilities',
            'sector':6
        },
        {
            'name_es':'Construcción e industrias manufactureras',
            'name_en': 'Construction and manufacturing industries',
            'sector':6
        },
        {
            'name_es':'Industrias energéticas',
            'name_en': 'Energy industries',
            'sector':6
        },
        {
            'name_es':'Actividades agrícolas, de silvicultura y de pesca',
            'name_en': 'Agricultural, forestry and fishing activities',
            'sector':6
        },
        {
            'name_es':'Fuentes no especificadas',
            'name_en': 'Unspecified sources',
            'sector':6
        },
        {
            'name_es':'Emisiones fugitivas provenientes de la minería, el procesamiento, el almacenamiento y el transporte de carbón',
            'name_en': 'Fugitive emissions from coal mining, processing, storage and transportation',
            'sector':6
        },
        {
            'name_es':'Emisiones fugitivas provenientes de los sistemas de petróleo y gas natural',
            'name_en': 'Fugitive emissions from oil and natural gas systems',
            'sector':6
        },
        {
            'name_es':'Por carretera',
            'name_en': 'By highway',
            'sector':7
        },
        {
            'name_es':'Ferroviario',
            'name_en': 'Ferroviario',
            'sector':7
        },
        {
            'name_es':'Navegación marítima, fluvial y lacustre',
            'name_en': 'Maritime, fluvial and lacustrine navigation',
            'sector':7
        },
        {
            'name_es':'Aviación',
            'name_en': 'Aviation',
            'sector':7
        },
        {
            'name_es':'Fuera de carretera',
            'name_en': 'Off road',
            'sector':7
        },
        {
            'name_es':'Disposición de residuos sólidos generados en la ciudad',
            'name_en': 'Disposal of solid waste generated in the city',
            'sector':8
        },
        {
            'name_es':'Tratamiento biológico de residuos generados en la ciudad',
            'name_en': 'Biological treatment of waste generated in the city',
            'sector':8
        },
        {
            'name_es':'Incineración y quema a cielo abierto de residuos generados en la ciudad',
            'name_en': 'Incineration and open burning of waste generated in the city',
            'sector':8
        },
        {
            'name_es':'Aguas residuales generadas en la ciudad',
            'name_en': 'Wastewater generated in the city',
            'sector':8
        },
        {
            'name_es':'Ganadería',
            'name_en': 'Cattle raising',
            'sector':9
        },
        {
            'name_es':'Uso de la Tierra',
            'name_en': 'Use of the Earth',
            'sector':9
        },
        {
            'name_es':'Fuentes agregadas y emisiones procedentes de fuentes del suelo distintas  al CO2',
            'name_en': 'Aggregate sources and emissions from sources other than CO2',
            'sector':9
        }
    ]

    # Clear current data
    GeographicLevel.objects.all().delete()
    RequiredLevel.objects.all().delete()
    RecognitionType.objects.all().delete()
    Sector.objects.all().delete()
    SubSector.objects.all().delete()

    # Insert seed data
    for gl in geographic_level:
        geo_level = GeographicLevel(level_es=gl.get('level_es'), level_en=gl.get('level_en'))
        geo_level.save()

    for rl in required_level:
        req_level = RequiredLevel(level_type_es=rl.get('level_type_es'), level_type_en=rl.get('level_type_en'))
        req_level.save()

    for rt in recognition_type:
        rec_type = RecognitionType(recognition_type_es=rt.get('recognition_type_es'), recognition_type_en=rt.get('recognition_type_en'))
        rec_type.save()

    for sec in sector:
        sector = Sector(name_es=sec.get('name_es'), name_en=sec.get('name_en'), geographicLevel_id = sec.get('geographicLevel_id'))
        sector.save()

    for ss in sub_sector:
        subsector = SubSector(name_es=ss.get('name_es'), name_en=ss.get('name_en'), sector_id=ss.get('sector'))
        subsector.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0002_auto_20180730_2101'),
    ]
    operations = [
        migrations.AddField(
            model_name='subsector',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='ppcn.Sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='geographicLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographicLevel', to='ppcn.GeographicLevel'),
        ),
        migrations.RunPython(insert_form_data)
    ]
