# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-01 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppcn', '0003_auto_20180730_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCNFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to='ppcn/files/%Y%m%d/%H%M%S')),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographicLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographicLevel', to='ppcn.GeographicLevel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='ppcn.Organization')),
                ('recognitionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognization', to='ppcn.RecognitionType')),
                ('requiredLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requiredLevel', to='ppcn.RequiredLevel')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='ppcn.Sector')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsector', to='ppcn.SubSector')),
                ('base_year', models.DateTimeField(null = False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PPCN',
                'verbose_name_plural': 'PPCNs',
            },
        ),
        migrations.AddField(
            model_name='ppcnfile',
            name='ppcn_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppcn.PPCN'),
        ),
        migrations.AddField(
            model_name='ppcnfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppcn_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
