# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0007_auto_20180821_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppcnfile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ppcnfile',
            name='name',
        ),
    ]
