# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0009_auto_20180827_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ciiu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
