# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20180513_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppcn', '0011_ppcnworkflowstep_ppcnworkflowstepfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=100, null=True)),
                ('current_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ChangeLog',
                'verbose_name_plural': 'ChangeLogs',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='ppcn',
            name='comments',
            field=models.ManyToManyField(blank=True, to='workflow.Comment'),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='ppcn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='ppcn.PPCN'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log_ppcn', to=settings.AUTH_USER_MODEL),
        ),
    ]
