# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-16 19:50
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0012_auto_20180911_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppcn',
            name='fsm_state',
            field=django_fsm.FSMField(default='PPCN_new', max_length=50, protected=True),
        ),
    ]
