# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0013_auto_20181116_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geiorganization',
            old_name='emision_OVV',
            new_name='emission_OVV',
        ),
        migrations.RemoveField(
            model_name='geiorganization',
            name='report_date',
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='report_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='report_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='gei_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppcn.GeiOrganization'),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='ovv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovv', to='mccr.OVV'),
        ),
    ]
