# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0014_auto_20181125_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeiActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=500)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gei_sector', to='ppcn.SubSector')),
                ('sub_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gei_sub_sector', to='ppcn.SubSector')),
            ],
        ),
        migrations.RenameField(
            model_name='geiorganization',
            old_name='emission_OVV',
            new_name='emission_ovv_date',
        ),
        migrations.RemoveField(
            model_name='geiorganization',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='geiorganization',
            name='report_date_end',
        ),
        migrations.RemoveField(
            model_name='geiorganization',
            name='report_date_start',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='base_year',
        ),
        migrations.RemoveField(
            model_name='geiorganization',
            name='base_year',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='geographicLevel',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='recognitionType',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='requiredLevel',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='ppcn',
            name='subsector',
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='report_year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='geographic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_level', to='ppcn.GeographicLevel'),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='recognition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognization', to='ppcn.RecognitionType'),
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='base_year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='ppcn',
            name='required_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_level', to='ppcn.RequiredLevel'),
        ),
        migrations.AlterField(
            model_name='ppcn',
            name='gei_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gei_organization', to='ppcn.GeiOrganization'),
        ),
        migrations.AlterField(
            model_name='ppcn',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='ppcn.Organization'),
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='gei_activity_types',
            field=models.ManyToManyField(to='ppcn.GeiActivityType'),
        ),
    ]
