# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-04 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0015_auto_20181210_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcn',
            options={'permissions': (('can_provide_information_ppcn', 'Can provide information ppcn'), ('user_CA_permission', 'user CA permission'), ('user_DCC_permission', 'user DCC permision'), ('user_executive_secretary_permission', 'user executive secretary permission')), 'verbose_name': 'PPCN', 'verbose_name_plural': 'PPCNs'},
        ),
    ]
