# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-18 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0017_addPermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppcn',
            options={'permissions': (('can_provide_information', 'Can provide information ppcn'), ('user_ca_permission', 'user CA permission PPCN'), ('user_dcc_permission', 'user DCC permision PPCN'), ('user_executive_secretary_permission', 'user executive secretary permission PPCN')), 'verbose_name': 'PPCN', 'verbose_name_plural': 'PPCNs'},
        ),
    ]
