# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0018_auto_20190318_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geiactivitytype',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gei_sector', to='ppcn.Sector'),
        ),
    ]
