# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0019_auto_20190718_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIIUCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciiu_code', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ciiu',
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_identification',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='organization',
            name='representative_legal_identification',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ciiucode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciiu_code', to='ppcn.Organization'),
        ),
    ]
