# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0019_auto_20190718_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_identification',
            field=models.CharField(max_length=12),
        ),
    ]
