# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0020_auto_20200507_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiogenicEmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=5, max_digits=20)),
                ('scope_1', models.CharField(blank=True, max_length=100, null=True)),
                ('scope_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Biogenic Emission',
                'verbose_name_plural': 'Biogenic Emissions',
            },
        ),
        migrations.CreateModel(
            name='GasReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_gases', models.TextField(blank=True, null=True)),
                ('cost_ghg_inventory', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost_ghg_inventory_currency', models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10)),
                ('cost_ovv_process', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost_ovv_process_currency', models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10)),
                ('biogenic_emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_report', to='ppcn.BiogenicEmission')),
            ],
            options={
                'verbose_name': 'Gas Report',
                'verbose_name_plural': 'Gas Report',
            },
        ),
        migrations.CreateModel(
            name='GasScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('report_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_scope', to='ppcn.GasReport')),
            ],
            options={
                'verbose_name': 'Gas Scope',
                'verbose_name_plural': 'Gas Scopes',
            },
        ),
        migrations.AlterModelOptions(
            name='geiactivitytype',
            options={'verbose_name': 'Gei Activity Type', 'verbose_name_plural': 'Gei Activity Types'},
        ),
        migrations.AlterModelOptions(
            name='quantifiedgas',
            options={'verbose_name': 'Quantified Gas', 'verbose_name_plural': 'Quantified Gases'},
        ),
        migrations.AddField(
            model_name='quantifiedgas',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=20)
        ),
        migrations.AlterField(
            model_name='quantifiedgas',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='gas_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gei_organization', to='ppcn.GasReport'),
        ),
        migrations.AddField(
            model_name='quantifiedgas',
            name='scope',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='gases', to='ppcn.GasScope')
        ),
    ]
