# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0021_auto_20200430_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_category', models.CharField(max_length=200, null=True)),
                ('buildings_number', models.IntegerField(null=True)),
                ('data_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('methodologies_complexity', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Category',
                'verbose_name_plural': 'Organization Categories',
            },
        ),
        migrations.AddField(
            model_name='geiorganization',
            name='organization_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gei_organization', to='ppcn.OrganizationCategory'),
        ),
    ]
