# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0021_auto_20200421_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppcn',
            name='organization_classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppcn', to='ppcn.OrganizationClassification'),
        ),
    ]
