# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-01 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0023_auto_20200525_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('request_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Number of Request per Year',
                'verbose_name_plural': 'Number of Request per Year',
            },
        ),
        migrations.AddField(
            model_name='ppcn',
            name='file_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='certificate_identification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='offset_cost_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='offset_scheme',
            field=models.CharField(choices=[('CER', 'CER'), ('VER', 'VER'), ('UCC', 'Unidades de Compesnsacion de Carbono')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='project_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='total_carbon_offset',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='total_offset_cost_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasremoval',
            name='removal_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasremoval',
            name='removal_cost_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasremoval',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='biogenic_emission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gas_report', to='ppcn.BiogenicEmission'),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ghg_inventory',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ghg_inventory_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ovv_process_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='geiactivitytype',
            name='activity_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='base_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='emission_ovv_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='ovv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovv', to='mccr.OVV'),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='report_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='representative_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='buildings_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='detail_reduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='emission',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='investment_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='total_emission',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='total_investment_currency',
            field=models.CharField(choices=[('CRC', 'Costa Rican colón'), ('USD', 'United States dollar')], max_length=10, null=True),
        ),
    ]
