# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0024_auto_20200601_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_representative_legal',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
