# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-06-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0025_organization_email_representative_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclassification',
            name='data_inventory_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='emission_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
