# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-11-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0028_catalogs_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='geiorganization',
            name='scope',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organizationclassification',
            name='methodologies_complexity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
