# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0029_auto_20201111_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogenicemission',
            name='scope_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biogenicemission',
            name='scope_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geiorganization',
            name='scope',
            field=models.TextField(null=True),
        ),
    ]
