# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-02-03 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0030_auto_20201216_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogenicemission',
            name='total',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='offset_cost',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='carbonoffset',
            name='total_offset_cost',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='gasremoval',
            name='removal_cost',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ghg_inventory',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ovv_process',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='organizationcategory',
            name='data_inventory_quantity',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='organizationcategory',
            name='emission_quantity',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='data_inventory_quantity',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='organizationclassification',
            name='emission_quantity',
            field=models.DecimalField(decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='quantifiedgas',
            name='value',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='investment',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='total_investment',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
