# Generated by Django 3.2 on 2021-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcn', '0031_auto_20210203_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasreport',
            name='cost_ghg_inventory',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
