# Generated by Django 3.2 on 2021-10-07 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitigation_action', '0017_auto_20210831_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationActionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('objective', models.CharField(max_length=3000, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('meta', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'verbose_name': 'Adaptation Action Information',
                'verbose_name_plural': 'Adaptation Action Information',
            },
        ),
        migrations.CreateModel(
            name='AdaptationActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adaptation Action Type',
                'verbose_name_plural': 'Adaptation Action Types',
            },
        ),
        migrations.CreateModel(
            name='ClimateThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeClimatedThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, null=True)),
                ('responsible_entity', models.CharField(max_length=200, null=True)),
                ('legal_identification', models.CharField(max_length=50, null=True)),
                ('elaboration_date', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_organization', to='mitigation_action.contact')),
            ],
            options={
                'verbose_name': 'Report Organization',
                'verbose_name_plural': 'Report Organizations',
            },
        ),
        migrations.CreateModel(
            name='AdaptationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.reportorganization')),
            ],
            options={
                'verbose_name': 'Adaptation Action',
                'verbose_name_plural': 'Adaptation Actions',
            },
        ),
    ]
