# Generated by Django 3.2 on 2021-10-18 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20211018_2156'),
        ('adaptation_action', '0002_activity_subtopics_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('responsible_entity', models.CharField(max_length=50, null=True)),
                ('other_entity', models.CharField(max_length=250, null=True)),
                ('action_code', models.CharField(max_length=3, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Implementation',
                'verbose_name_plural': 'Implementations',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
        migrations.AlterModelOptions(
            name='climatethreat',
            options={'verbose_name': 'Type Climated Threat', 'verbose_name_plural': 'Type Climated Threats'},
        ),
        migrations.AlterModelOptions(
            name='typeclimatedthreat',
            options={'verbose_name': 'Type Climated Threat', 'verbose_name_plural': 'Type Climated Threats'},
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.activity'),
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='climate_threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.climatethreat'),
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='adaptation_action_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action_informatio', to='adaptation_action.adaptationactiontype'),
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='type_climated_threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_threat', to='adaptation_action.typeclimatedthreat'),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportorganization',
            name='entity_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='typeclimatedthreat',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='typeclimatedthreat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeclimatedthreat',
            name='name',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='typeclimatedthreat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adaptationaction',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='general.address'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.instrument'),
        ),
    ]
