# Generated by Django 3.2 on 2021-11-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0002_auto_20211102_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Impact',
                'verbose_name_plural': 'General Impact',
            },
        ),
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Report',
                'verbose_name_plural': 'General Report',
            },
        ),
        migrations.CreateModel(
            name='IndicatorSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('name', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicator Source',
                'verbose_name_plural': 'Indicator Source',
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_status', models.CharField(max_length=25, null=True)),
                ('progress_monitoring', models.CharField(max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progress Log',
                'verbose_name_plural': 'Progress Logs',
            },
        ),
        migrations.CreateModel(
            name='TemporalityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporality Impact',
                'verbose_name_plural': 'Temporality Impact',
            },
        ),
        migrations.CreateModel(
            name='IndicatorMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('update_date', models.DateField(null=True)),
                ('data_to_update', models.CharField(max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_monitoring', to='adaptation_action.indicatoradaptation')),
                ('indicator_source', models.ManyToManyField(blank=True, related_name='indicator_monitoring', to='adaptation_action.IndicatorSource')),
            ],
            options={
                'verbose_name': 'Indicator Monitoring',
                'verbose_name_plural': 'Indicator Monitoring',
            },
        ),
        migrations.CreateModel(
            name='ActionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_equality', models.CharField(max_length=3, null=True)),
                ('gender_equality_description', models.CharField(max_length=3000, null=True)),
                ('unwanted_action', models.CharField(max_length=3, null=True)),
                ('unwanted_action_description', models.CharField(max_length=3000, null=True)),
                ('general_impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_impact', to='adaptation_action.generalimpact')),
                ('ods', models.ManyToManyField(blank=True, related_name='action_impact', to='adaptation_action.ODS')),
                ('temporality_impact', models.ManyToManyField(blank=True, related_name='action_impact', to='adaptation_action.TemporalityImpact')),
            ],
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='action_impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.actionimpact'),
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='general_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.generalreport'),
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='indicator_monitoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.indicatormonitoring'),
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='progress_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.progresslog'),
        ),
    ]
