# Generated by Django 3.2 on 2021-12-20 22:57

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0005_auto_20211215_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationaction',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=100, protected=True),
        ),
    ]
