# Generated by Django 3.2 on 2022-03-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0007_catalogs_adaptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatoradaptation',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
