# Generated by Django 3.2 on 2022-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0007_catalogs_adaptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportorganizationtype',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='indicatoradaptation',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportorganization',
            name='responsible_entity',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
