# Generated by Django 3.2 on 2022-04-07 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptation_action', '0008_auto_20220405_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=100, null=True)),
                ('current_status', models.CharField(max_length=100)),
                ('adaptation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='adaptation_action.adaptationaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action_change_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChangeLog',
                'verbose_name_plural': 'ChangeLogs',
                'ordering': ('date',),
            },
        ),
    ]
