# Generated by Django 3.2 on 2022-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0009_changelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator',
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='indicator',
            field=models.ManyToManyField(blank=True, related_name='adaptation_action', to='adaptation_action.IndicatorAdaptation'),
        ),
    ]
