# Generated by Django 3.2 on 2022-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0010_auto_20220413_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator',
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='indicator',
            field=models.ManyToManyField(blank=True, related_name='adaptation_action', to='adaptation_action.IndicatorAdaptation'),
        ),
    ]
