# Generated by Django 3.2 on 2022-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20201028_1950'),
        ('adaptation_action', '0010_auto_20220413_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationaction',
            name='comments',
            field=models.ManyToManyField(blank=True, to='workflow.Comment'),
        ),
    ]
