# Generated by Django 3.2 on 2022-05-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0011_adaptationaction_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='start_date',
        ),
    ]
