# Generated by Django 3.2 on 2022-08-24 22:57

import adaptation_action.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptation_action', '0011_adaptationaction_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ndcarea',
            name='other',
        ),
        migrations.RemoveField(
            model_name='ndccontribution',
            name='other',
        ),
        migrations.AddField(
            model_name='actionimpact',
            name='data_to_update_file_action_impact',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='description_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='exposed_elements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_description_climate_threat',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_exposed_elements',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_vulnerability_climate_threat',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='other_type_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='vulnerability_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='financeadaptation',
            name='instrument_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='financeadaptation',
            name='year',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='adaptation_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='adaptation_action.adaptationaction'),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='additional_information_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='methodological_detail_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='data_to_update_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='other_indicator_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='support_information',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='adaptationaction',
            name='activity',
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='adaptation_action', to='adaptation_action.Activity'),
        ),
        migrations.RemoveField(
            model_name='climatethreat',
            name='type_climate_threat',
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='type_climate_threat',
            field=models.ManyToManyField(blank=True, related_name='climate_threat', to='adaptation_action.TypeClimateThreat'),
        ),
        migrations.RemoveField(
            model_name='informationsource',
            name='type_information',
        ),
        migrations.AddField(
            model_name='informationsource',
            name='type_information',
            field=models.ManyToManyField(blank=True, related_name='information_source', to='adaptation_action.InformationSourceType'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(null=True)),
                ('contact_position', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('institution', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_adaptation_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterField(
            model_name='indicatoradaptation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_adaptation', to='adaptation_action.contact'),
        ),
        migrations.AlterField(
            model_name='reportorganization',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_organization', to='adaptation_action.contact'),
        ),
    ]
