# Generated by Django 3.2 on 2022-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0011_adaptationaction_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='duration',
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='description_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='exposed_elements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='other_type_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='vulnerability_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='climatethreat',
            name='type_climate_threat',
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='type_climate_threat',
            field=models.ManyToManyField(blank=True, related_name='climate_threat', to='adaptation_action.TypeClimateThreat'),
        ),
    ]
