# Generated by Django 3.2 on 2022-08-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0011_auto_20220426_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator',
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='adaptation_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='adaptation_action.adaptationaction'),
        ),
    ]
