# Generated by Django 3.2 on 2022-08-24 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adaptation_action', '0011_adaptationaction_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='generalreport',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='implementation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ndcarea',
            name='other',
        ),
        migrations.RemoveField(
            model_name='ndccontribution',
            name='other',
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='description_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='exposed_elements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='other_type_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='vulnerability_climate_threat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='financeadaptation',
            name='instrument_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='adaptation_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to='adaptation_action.adaptationaction'),
        ),
        migrations.RemoveField(
            model_name='climatethreat',
            name='type_climate_threat',
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='type_climate_threat',
            field=models.ManyToManyField(blank=True, related_name='climate_threat', to='adaptation_action.TypeClimateThreat'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(null=True)),
                ('contact_position', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('institution', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_adaptation_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterField(
            model_name='indicatoradaptation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_adaptation', to='adaptation_action.contact'),
        ),
        migrations.AlterField(
            model_name='reportorganization',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_organization', to='adaptation_action.contact'),
        ),
    ]
