# Generated by Django 3.2 on 2022-08-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0012_auto_20220824_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='indicator_monitoring',
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='adaptation_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_monitoring', to='adaptation_action.adaptationaction'),
        ),
    ]
