# Generated by Django 3.2 on 2022-07-19 22:05

import adaptation_action.models
from django.db import migrations, models
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0012_auto_20220624_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionimpact',
            name='data_to_update_file_action_impact',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_description_climate_threat',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_exposed_elements',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_vulnerability_climate_threat',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='additional_information_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='methodological_detail_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='data_to_update_file',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.RemoveField(
            model_name='adaptationaction',
            name='activity',
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='activity',
            field=models.ManyToManyField(blank=True, related_name='adaptation_action', to='adaptation_action.Activity'),
        ),
    ]
