# Generated by Django 3.2 on 2022-08-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0013_auto_20220719_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeadaptation',
            name='year',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='other_indicator_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='support_information',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='informationsource',
            name='type_information',
        ),
        migrations.AddField(
            model_name='informationsource',
            name='type_information',
            field=models.ManyToManyField(blank=True, related_name='information_source', to='adaptation_action.InformationSourceType'),
        ),
    ]
