# Generated by Django 3.2 on 2022-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0013_auto_20220829_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeadaptation',
            name='currency',
            field=models.TextField(null=True),
        ),
    ]
