# Generated by Django 3.2 on 2022-08-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0014_auto_20220812_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='description',
        ),
    ]
