# Generated by Django 3.2 on 2022-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0015_adaptationaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationaction',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
