# Generated by Django 3.2 on 2023-02-28 20:06

import adaptation_action.models
from django.db import migrations, models
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0016_adaptationaction_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitedPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benefited Population',
                'verbose_name_plural': 'Benefited Populations',
            },
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='expected_result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='potential_co_benefits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='description_losses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='description_risks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_description_losses',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='climatethreat',
            name='file_description_risks',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='file_base_line',
            field=models.FileField(null=True, storage=general.storages.PrivateMediaStorage(), upload_to=adaptation_action.models.directory_path),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='indicator_base_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adaptationactioninformation',
            name='benefited_population',
            field=models.ManyToManyField(blank=True, related_name='adaptation_action_information', to='adaptation_action.BenefitedPopulation'),
        ),
    ]
