# Generated by Django 3.2 on 2023-02-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0016_adaptationaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatoradaptation',
            name='time_series_available',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='indicatormonitoring',
            name='reporting_period',
            field=models.DateField(null=True),
        ),
    ]
