# Generated by Django 5.1.5 on 2025-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0018_insert_benefited_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='other_entity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='responsible_entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
