# Generated by Django 5.1.5 on 2025-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0018_insert_benefited_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatoradaptation',
            name='associated_meta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicatoradaptation',
            name='same_contact_info_as_registration',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
