# Generated by Django 5.1.5 on 2025-07-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0019_indicatoradaptation_associated_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Group',
                'verbose_name_plural': 'Category Groups',
            },
        ),
        migrations.CreateModel(
            name='CategoryResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Results',
                'verbose_name_plural': 'Category Results',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensions',
            },
        ),
        migrations.CreateModel(
            name='SustainableImpactDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sustainable Impact Duration',
                'verbose_name_plural': 'Sustainable Impact Durations',
            },
        ),
        migrations.CreateModel(
            name='SustainableImpactScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sustainable Impact Scale',
                'verbose_name_plural': 'Sustainable Impact Scales',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('other_category', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adaptation_action.categorygroup')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_group', to='adaptation_action.dimension'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_results', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='adaptation_action.categoryresults')),
            ],
            options={
                'verbose_name': 'Results',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_type', models.BooleanField(default=False, null=True)),
                ('pertinent', models.BooleanField(default=False, null=True)),
                ('relevant', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sustainable_development_impact', to='adaptation_action.category')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sustainable_development_impact', to='adaptation_action.results')),
            ],
            options={
                'verbose_name': 'Sustainable Development Impact',
                'verbose_name_plural': 'Sustainable Development Impacts',
            },
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='sustainable_development_impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.sustainabledevelopmentimpact'),
        ),
        migrations.AddField(
            model_name='categoryresults',
            name='sustainable_duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='adaptation_action.sustainableimpactduration'),
        ),
        migrations.AddField(
            model_name='categoryresults',
            name='sustainable_scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='adaptation_action.sustainableimpactscale'),
        ),
    ]
