# Generated by Django 5.1.5 on 2025-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0019_indicatoradaptation_associated_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationAxisRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True)),
                ('value', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adaptation Axis Relation',
                'verbose_name_plural': 'Adaptation Axis Relations',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='adaptation_axis_relation',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='adaptation_action.adaptationaxisrelation'),
        ),
    ]
