# Generated by Django 5.1.5 on 2025-08-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0019_indicatoradaptation_associated_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatoradaptation',
            name='geographic_coverage',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('PROVINCIAL', 'Provincial'), ('CANTONAL', 'Cantonal'), ('DISTRICT', 'District'), ('OTHER', 'Other')], default='NATIONAL', max_length=255, null=True),
        ),
    ]
