# Generated by Django 5.1.5 on 2025-08-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0021_adaptationaction_final_result_processes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='specific_impact',
        ),
        migrations.AddField(
            model_name='processes',
            name='specific_impact',
            field=models.ManyToManyField(blank=True, related_name='processes', to='adaptation_action.specificimpact'),
        ),
    ]
