# Generated by Django 5.1.5 on 2025-08-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0022_remove_processes_specific_impact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationaction',
            name='category_option',
        ),
        migrations.CreateModel(
            name='QuantifiedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.CharField(max_length=70, null=True)),
                ('expected_value', models.CharField(max_length=70, null=True)),
                ('accumulated_value', models.CharField(max_length=70, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantified_indicator', to='adaptation_action.indicatoradaptation')),
            ],
            options={
                'verbose_name': 'Quantified Indicator',
                'verbose_name_plural': 'Quantified Indicators',
            },
        ),
        migrations.AddField(
            model_name='adaptationaction',
            name='category_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_action', to='adaptation_action.categoryoption'),
        ),
    ]
