# Generated by Django 5.1.5 on 2025-08-28 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0023_remove_adaptationaction_category_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysection',
            name='accumulated_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='base_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='expected_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='categorysection',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_section', to='adaptation_action.indicatoradaptation'),
        ),
        migrations.AddField(
            model_name='scale',
            name='accumulated_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='base_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='expected_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale', to='adaptation_action.indicatoradaptation'),
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='accumulated_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='base_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='expected_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_impacts', to='adaptation_action.indicatoradaptation'),
        ),
        migrations.DeleteModel(
            name='QuantifiedIndicator',
        ),
    ]
