# Generated by Django 5.1.5 on 2025-08-28 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0024_categorysection_accumulated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheroption',
            name='accumulated_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='otheroption',
            name='base_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='otheroption',
            name='expected_value',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='otheroption',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_option', to='adaptation_action.indicatoradaptation'),
        ),
    ]
