# Generated by Django 5.1.5 on 2025-09-12 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation_action', '0026_barrieroption_otherbarrieroption_and_more'),
        ('general', '0010_insert_caracteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='specificimpact',
            name='category_ct',
        ),
        migrations.AddField(
            model_name='specificimpact',
            name='characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_impacts', to='general.characteristic'),
        ),
    ]
