# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 03:03
from __future__ import unicode_literals

from django.db import migrations

def insert_review_status(apps, schema_editor):
    # Models
    ReviewStatus = apps.get_model('workflow', 'ReviewStatus')

    # Data
    review_status_data = [
        'submitted',
        'in-review',
        'on-change',
        'approved',
        'rejected'
    ]

    # Clear current data
    ReviewStatus.objects.all().delete()

    # Insert seed data
    for rs in review_status_data:
        rev_status = ReviewStatus(status=rs)
        rev_status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_review_status)
    ]
