# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20180503_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=3000),
        ),
    ]
