# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-28 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0003_auto_20180513_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(
            model_name='comment',
            name='form_section',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='field',
            field=models.CharField(max_length=1048, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='fsm_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='review_number',
            field=models.IntegerField()
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2048),
        ),
    ]
