# Generated by Django 3.2 on 2022-03-10 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import general.storages
import report_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitigation_action', '0017_auto_20210831_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsm_state', django_fsm.FSMField(default='new', max_length=100, protected=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('calculation_methodology', models.CharField(blank=True, max_length=1000, null=True)),
                ('measurement_frequency', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('biannual', 'Biannual'), ('quartely', 'Quartely')], max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('geographic_coverage', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('PROVINCIAL', 'Provincial'), ('CANTONAL', 'Cantonal'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('disaggregation', models.TextField(null=True)),
                ('limitation', models.TextField(null=True)),
                ('additional_information', models.TextField(null=True)),
                ('statistical_operation', models.TextField(null=True)),
                ('contact_annotation', models.TextField(null=True)),
                ('other_data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('other_classifier', models.CharField(blank=True, max_length=255, null=True)),
                ('report_information', models.CharField(choices=[('statistics_or_variable', 'Statistics or Variable'), ('indicator', 'Indicator'), ('data_base', 'Data Base')], max_length=100)),
                ('have_line_base', models.BooleanField(default=False)),
                ('line_base_type', models.CharField(blank=True, choices=[('upload_files', 'Upload Files'), ('individual_report', 'Individual Report'), ('url', 'url')], max_length=100, null=True)),
                ('line_base_report', models.TextField(blank=True, null=True)),
                ('have_quality_element', models.BooleanField(default=False)),
                ('quality_element_description', models.TextField(blank=True, null=True)),
                ('transfer_data_with_sinamecc', models.BooleanField(default=False)),
                ('transfer_data_with_sinamecc_description', models.TextField(blank=True, null=True)),
                ('report_data_type', models.CharField(blank=True, choices=[('upload_files', 'Upload Files'), ('individual_report', 'Individual Report'), ('url', 'url')], max_length=100, null=True)),
                ('individual_report_data', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classifier', models.ManyToManyField(related_name='report_data', to='mitigation_action.Classifier')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_data', to='mitigation_action.contact')),
                ('data_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_data', to='mitigation_action.thematiccategorizationtype')),
                ('information_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_data', to='mitigation_action.informationsourcetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Data',
                'verbose_name_plural': 'Report Data',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('file', models.FileField(blank=True, null=True, storage=general.storages.PrivateMediaStorage(), upload_to=report_data.models.directory_path)),
                ('report_type', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='report_data.reportdata')),
            ],
            options={
                'verbose_name': 'Report File',
                'verbose_name_plural': 'Report Files',
            },
        ),
        migrations.CreateModel(
            name='ReportDataChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.TextField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_data_change_log', to=settings.AUTH_USER_MODEL)),
                ('report_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_data_change_log', to='report_data.reportdata')),
            ],
            options={
                'verbose_name': 'Report Data Changelog',
                'verbose_name_plural': 'Report Data Changelogs',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='report_data.reportdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report',
            },
        ),
    ]
