# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(default='/media/foo', upload_to=''),
            preserve_default=False,
        ),
    ]
