# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0002_auto_20180307_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to='report_data/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
