# Generated by Django 3.2 on 2023-03-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0002_auto_20220420_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
