# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0003_auto_20180307_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ReportFileVersion',
                'verbose_name_plural': 'ReportFileVersions',
            },
        ),
        migrations.AddField(
            model_name='reportfile',
            name='versions',
            field=models.ManyToManyField(to='report_data.ReportFileVersion'),
        ),
    ]
