# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0004_auto_20180314_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfileversion',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportfileversion',
            name='version',
            field=models.CharField(default='v1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
