# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0005_auto_20180315_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfileversion',
            name='file',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
