# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0006_reportfileversion_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='file',
        ),
        migrations.AlterField(
            model_name='reportfileversion',
            name='file',
            field=models.FileField(upload_to='report_data/%Y%m%d/%H%M%S'),
        ),
    ]
