# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0004_reportfile_user'),
        ('report_data', '0008_auto_20180320_0427'),
    ]

    operations = [
    ]
