# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_data', '0009_merge_20180322_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfileversion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_file_version', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
