# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0010_reportfileversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
