# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import general.storages


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0011_auto_20180322_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfileversion',
            name='file',
            field=models.FileField(storage=general.storages.PrivateMediaStorage(), upload_to='report_data/%Y%m%d/%H%M%S'),
        ),
    ]
