# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0012_auto_20180517_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('report_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_data.ReportFile')),
            ],
            options={
                'verbose_name': 'ReportFileMetadata',
                'verbose_name_plural': 'ReportFileMetadata',
            },
        ),
    ]
