# Generated by Django 3.2 on 2021-10-22 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation_action', '0017_auto_20210831_0331'),
        ('report_data', '0013_reportfilemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='mitigation_action.contact'),
        ),
    ]
