# Generated by Django 3.2 on 2022-01-25 03:20

from django.db import migrations, models
import django.db.models.deletion
import general.storages
import report_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0014_auto_20211101_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='report_file',
        ),
        migrations.AddField(
            model_name='reportdata',
            name='individual_report_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='line_base_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='line_base_type',
            field=models.CharField(blank=True, choices=[('upload_files', 'Upload Files'), ('individual_report', 'Individual Report'), ('url', 'url')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='report_data_type',
            field=models.CharField(blank=True, choices=[('upload_files', 'Upload Files'), ('individual_report', 'Individual Report'), ('url', 'url')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=general.storages.PrivateMediaStorage(), upload_to=report_data.models.directory_path),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='report_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='report_data.reportdata'),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='report_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ReportFileVersion',
        ),
    ]
