# Generated by Django 3.2 on 2022-02-03 15:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('report_data', '0015_auto_20220125_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfilemetadata',
            name='fsm_state',
            field=django_fsm.FSMField(default='new', max_length=100, protected=True),
        ),
    ]
