openapi: 3.0.0
info:
  title: Sinamecc API
  description: API documentation for Sinamecc backend
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local server

tags:
  - name: mitigation-action
    description: Mitigation action
  - name: adaptation-action
    description: Adaptation action
  - name: report-data
    description: for testing backend
  - name: users
    description: User management
  - name: roles
    description: Role management
  - name: general
    description: General
  - name: indicator
    description: Indicators

paths:
  ## User Definitions
  /token/:
    $ref: "./components/paths/users/jwt-token.yaml"
  /users/{id}:
    $ref: "./components/paths/users/record.yaml#/user"
  /users:
    $ref: "./components/paths/users/record.yaml#/user-list"
  /users/me:
    $ref: "./components/paths/users/record.yaml#/user-me"
  /users/roles:
    $ref: "./components/paths/users/roles.yaml#/users-roles"
  /users/{id}/roles:
    $ref: "./components/paths/users/roles.yaml#/user-roles"
  /users/change-password-request:
    $ref: "./components/paths/users/change-password-request.yaml"
  /users/change-password:
    $ref: "./components/paths/users/change-password.yaml"
  
  ## Mitigation Action Definitions
  /mitigation-action/{id}/:
    $ref: "./components/paths/mitigation-actions/record.yaml"
  /mitigation-action/:
    $ref: "./components/paths/mitigation-actions/record-list.yaml"
  /mitigation-action/{id}/attachments:
    $ref: "./components/paths/mitigation-actions/attachments.yaml#/attachments"

  ## Adaptation Action Definitions
  /adaptation-action/{id}/:
    $ref: "./components/paths/adaptation-actions/record.yaml"
  /adaptation-action/:
    $ref: "./components/paths/adaptation-actions/record-list.yaml"

  #Dimension
  /general/dimension/:
    $ref: "./components/paths/general/record.yaml#/dimension-list"

  #Category Group
  /general/category_group/:
    $ref: "./components/paths/general/record.yaml#/category-group-list"
  
  #Category
  /general/category/:
    $ref: "./components/paths/general/record.yaml#/category-list"

  #Category_CT
  /general/category_ct/:
    $ref: "./components/paths/general/record.yaml#/category-ct-list"

  #Characteristic
  /general/characteristic/:
    $ref: "./components/paths/general/record.yaml#/characteristic-list"

  #Adaptation Indicators
  /adaptation-action/all_indicator/{id}/:
    $ref: "./components/paths/general/record.yaml#/aa-indicator"

  /adaptation-action/indicator/:
    $ref: "./components/paths/general/record.yaml#/aa-create-indicator"

components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      name: Authorization
      in: header
